apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-kube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-kube-app
  template:
    metadata:
      labels:
        app: rust-kube-app
    spec:
      containers:
        - name: rust-kube-app
          image: rust-kube-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
